import turtle

flag = turtle.Turtle() 
flag.speed(10)
flag.pensize(3)

flag.begin_fill()
flag.forward(200)
flag.left(90)
flag.forward(75)
flag.left(90)
flag.forward(200)
flag.left(90)
flag.forward(75)
flag.pencolor("white")
flag.color("black")
flag.fillcolor("black")
flag.end_fill()

flag.penup()
flag.forward(10)
flag.pendown()

flag.begin_fill()
flag.forward(75)
flag.left(90)
flag.forward(200)
flag.left(90)
flag.forward(75)
flag.left(90)
flag.forward(200)
flag.pencolor("white")
flag.color("red")
flag.fillcolor("red")
flag.end_fill()

flag.penup()
flag.pendown()
flag.forward(4)


flag.begin_fill()
flag.left(90)
flag.forward(160)
flag.left(90)
flag.forward(200)
flag.left(90)
flag.forward(75)
flag.left(90)
flag.forward(200)
flag.pencolor("white")
flag.color("white")
flag.fillcolor("green")
flag.end_fill()

turtle.setpos(80, -50)
turtle.shape("circle")
turtle.fillcolor("red")
turtle.shapesize(12, 5.6, 0.4)

#### INTERNAL SHAPES INSIDE THE SHIELD OF KENYA
flag.goto(110, -80)
flag.right(90)
flag.penup()
flag.forward(100)
flag.pendown()
flag.begin_fill()
flag.circle(10)
flag.pencolor("white")
flag.color("white")
flag.fillcolor("white")
flag.end_fill()

flag.penup()
flag.left(80)
flag.forward(50)
flag.pendown()
flag.begin_fill()
flag.circle(10)
flag.pencolor("white")
flag.color("white")
flag.fillcolor("white")
flag.end_fill()

flag.penup()
flag.goto(61, -119)
flag.pendown()
flag.begin_fill()
flag.circle(10)
flag.pencolor("white")
flag.color("white")
flag.fillcolor("white")
flag.end_fill()

flag.penup()
flag.left(170)
flag.forward(45)
flag.pendown()
flag.begin_fill()
flag.circle(10)
flag.pencolor("white")
flag.color("white")
flag.fillcolor("white")
flag.end_fill()

flag.penup()
flag.goto(29,-94)
flag.begin_fill()
flag.left(69)
flag.circle(70, 85)
flag.pendown()
flag.fillcolor("black")
flag.pencolor("white")
flag.color("black")
flag.end_fill()

flag.penup()
flag.goto(122,-98)
flag.begin_fill()
flag.right(87)
flag.circle(70, 85)
flag.pendown()
flag.fillcolor("black")
flag.pencolor("white")
flag.color("black")
flag.end_fill()

x = (186, 67)
y = (123, 19)

flag.penup()
flag.goto(x)
flag.pendown()
flag.goto(y)
flag.begin_fill()
flag.color("white")
flag.width(6)
flag.left(7)
flag.back(20)
flag.penup()
flag.goto(y)
flag.pendown()
flag.left(-54)
flag.forward(20)
flag.forward(5)
flag.color("white")
flag.pencolor("white")
flag.fillcolor("white")
flag.end_fill()

turtle.done()